#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

URL="https://suitecrm.com/download/166/suite89/566057/suitecrm-8-9-2.zip"
dl $URL /usr/local/src
